version: '3'

volumes:
  base-data:
  db-data:
  nginx-data:
  redis-data:

services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    restart: always
    ports:
      - '5431:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    restart: always
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        env: ${ENV:-dev}
    ports:
      - "8666:8000"
    command: |
        bash -c "
        while !</dev/tcp/db/5432; do sleep 1; done;
        alembic upgrade head &&
        gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --log-level=debug --timeout=120 --reload"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - base-data:/data
      - ./backend/:/code

  nginx:
    restart: always
    ports:
      - "0.0.0.0:80:80"
    env_file:
      - .env
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
        - nginx-data:/etc/letsencrypt

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6479:6379"
    volumes:
      - redis-data:/data
