---

version: '3.7'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ./Dockerfile
      args:
        env: "test"
    command: |
        bash -c "
        while !</dev/tcp/db-test/5432; do sleep 1; done;
        pytest --cov-report=xml:/data/coverage.xml --cov=src/ .""
    environment:
      - PYTHONUNBUFFERED=0
      - PROJECT_NAME=test
      - USERNAME=test
      - PASSWORD=test
      - CLIENT_ID=test
      - CLIENT_SECRET=test
      - BOT_NAME=tag-youre-it-bot
      - VERSION=v1
      - DEVELOPER=nickatnight
      - ENV=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db-test
    depends_on:
      - db-test
    expose:
      - "8000"
    volumes:
      - /data:/data  # to access coverage.xml

  db-test:
    image: postgres:15-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db-test
