---

name: pull-request

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: nickatnight/gha-workflows/.github/workflows/pre-commit.yml@main

  unit-tests:
    needs: [lint]
    uses: ./.github/workflows/unit-tests.yml
